// src/app/icons.ts
import { addIcons } from 'ionicons';
import { 
  add,
  addOutline,
  close,
  closeOutline,
  create,
  createOutline,
  trash,
  trashOutline,
  analytics,
  analyticsOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  pauseCircle,
  pauseCircleOutline,
  pause,
  pauseOutline,
  play,
  playOutline,
  warning,
  warningOutline,
  logOut,
  logOutOutline,
  hardwareChip,
  hardwareChipOutline,
  chevronDownCircle,
  chevronDownCircleOutline,
  menu,
  menuOutline
} from 'ionicons/icons';

export function registerIcons() {
  addIcons({
    'add': add,
    'add-outline': addOutline,
    'close': close,
    'close-outline': closeOutline,
    'create': create,
    'create-outline': createOutline,
    'trash': trash,
    'trash-outline': trashOutline,
    'analytics': analytics,
    'analytics-outline': analyticsOutline,
    'checkmark-circle': checkmarkCircle,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'pause-circle': pauseCircle,
    'pause-circle-outline': pauseCircleOutline,
    'pause': pause,
    'pause-outline': pauseOutline,
    'play': play,
    'play-outline': playOutline,
    'warning': warning,
    'warning-outline': warningOutline,
    'log-out': logOut,
    'log-out-outline': logOutOutline,
    'hardware-chip': hardwareChip,
    'hardware-chip-outline': hardwareChipOutline,
    'chevron-down-circle': chevronDownCircle,
    'chevron-down-circle-outline': chevronDownCircleOutline,
    'menu': menu,
    'menu-outline': menuOutline,
    'information-circle': informationCircleOutline,
    'information-circle-outline': informationCircleOutline,
    'information-outline': informationOutline
  });
}